apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  values:
    installCRDs: true
