apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: 4.8.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  values:
    controller:
      metrics:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: true
        prometheus.io/port: 10254
