apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
spec:
  interval: 1h
  chart:
    spec:
      chart: dex
      version: 0.15.3
      sourceRef:
        kind: HelmRepository
        name: dex
  values:
    envVars:
    - name: GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: github-client
          key: client-id
    - name: GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: github-client
          key: client-secret
    config:
      issuer: https://${dex_domain}
      storage:
        type: memory
      connectors:
      - type: github  # https://dexidp.io/docs/connectors/github/#configuration
        id: github
        name: GitHub
        config:
          clientID: $GITHUB_CLIENT_ID
          clientSecret: $GITHUB_CLIENT_SECRET
          redirectURI: https://${dex_domain}/callback
          orgs:
          - name: ${github_org_name}
            teams:
            - ${github_org_team_a_name}
      staticClients:
      - id: ${weave_gitops_client_id}
        secret: ${weave_gitops_client_secret}
        name: ${weave_gitops_app_name}
        redirectURIs:
        - https://${weave_gitops_domain}/oauth2/callback
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
      - host: ${dex_domain}
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - hosts:
        - ${dex_domain}
        secretName: ${dex_domain_secret_name}
